### PR TITLE
fix. Repair the problem of inaccurate logs in ipv6 mode

### PR DESCRIPTION
**Pull request by sxueck**
This PR solves the problem that the logs are not displayed properly when listening to IPv6 addresses

### CODE REVIEW

**Comment by sxueck** [comment]
#74

**Comment by Mohammed90** [comment]
I foresee this growing in complexity. Won't it be better if the string matching & manipulation hack is replaced with proper field logger? This way the logging of the user and IP address is enabled, without having to parse regexp at every request, without placing restriction on users to surround IPv6 with quotes, and get the added benefit of proper logging throughout the app.

**Comment by sxueck** [comment]
**users to surround IPv6 with quotes** it's because when viper parses the configuration file, the absence of quotation marks causes panic errors [code](https://github.com/hacdias/webdav/blob/9a4b378b32ea04b5c45b727713837e34435d0ef5/cmd/root.go#L87)
Also, from a project maintenance point of view, the performance loss from wrapping a regular matching function for use is minimal.
Because the bottleneck of project performance is not in the cpu, but in the I/O, what do you think??

**Comment by sxueck** [comment]
@hacdias ping

**Comment by hacdias** [comment]
Sorry for the late reply. Just noticed I didn't have notifications turned on for this repository - weird.

I agree with @Mohammed90: isn't it simpler just replace by a field logger? The code would get even cleaner and still get the desired output.

**Comment by Mohammed90** [comment]
Another data point, by simply opting for field logger, another bug (#82) is resolved. There will be no need to keep the map.

**Comment by Mohammed90** [comment]
@sxueck, can you check the other PR #87? I took a shot at it

**Pull request closed without merging**
