### PR TITLE
chore: fix circleci release config

### PR DESCRIPTION
**Pull request by Mohammed90**
Amendments based on [the Go orb docs](https://circleci.com/orbs/registry/orb/circleci/go#commands-install). Let's hope this works 🤞

### CODE REVIEW

**Comment by Mohammed90** [comment]
This is maddening. Any objection to switching to Github Actions?

**Comment by hacdias** [comment]
Not really eheh, i can add you to push permissions

**Comment by Mohammed90** [comment]
> Not really eheh, i can add you to push permissions

Thanks! I have drafted the workflow files and will push them later. Just please add the docker hub PAT/password as secret so I can use it in the workflow.

**Comment by hacdias** [comment]
What variable names do you prefr?

**Comment by Mohammed90** [comment]
> What variable names do you prefr?

DOCKER_USERNAME

**Pull request merged**
