### PR TITLE
chore: Switch to Github Actions

### PR DESCRIPTION
**Pull request by Mohammed90**
This better work, otherwise...

### CODE REVIEW

**Comment by Mohammed90** [comment]
@hacdias, last 2 actions to close the CI issue 🙂 
- Disable CircleCI check (in Settings, under either Integration or Branches or both)
- Push the latest tag (perhaps I'm able to do that?)

**Comment by hacdias** [comment]
@Mohammed90 I just disabled the circleci check. Please release!!! 🔥

**Comment by Mohammed90** [comment]
> @Mohammed90 I just disabled the circleci check. Please release!!! 🔥 

Done. The release is job is successful now and the logs indicate it pushed everything to Github & Docker Hub. The release is marked as draft os GitHub for now. However, Docker Hub still says 3.0.0 🤔

**Comment by hacdias** [comment]
> However, Docker Hub still says 3.0.0 

Yeah, that's quite odd! I couldn't find why

**Pull request merged**
