### PR TITLE
multi scopes for each user

### PR DESCRIPTION
**Pull request by Travalone**

### CODE REVIEW

**Comment by Mohammed90** [comment]
This does more than apply multi scopes for each user. Was this a mistake?

**Comment by Travalone** [comment]
> This does more than apply multi scopes for each user. Was this a mistake?
Not clear what u mean. I just adjusted the config options according to my personal habit, imitating FileZilla.
My main purpose is the multi scopes for each user, and I used the Prefix to implement it. 
Not familiar with golang, I got the official webdav lib and modified some private methods to public, in order to return a virtual dir of the scopes when requesting the "/" url. 
In addition, serveral src files were renamed to avoid the duplicate and some config options I thought useless were canceled.

**Comment by Mohammed90** [comment]
> > This does more than apply multi scopes for each user. Was this a mistake?
> 
> Not clear what u mean. I just adjusted the config options according to my personal habit, imitating FileZilla.
> My main purpose is the multi scopes for each user, and I used the Prefix to implement it.

Click on the `Files changed` tab and see all your changes there. You've deleted many necessary files and code, renamed/removed the proper module path from being `github.com/hacdias/webdav/v3`, added your IDE's files, and much more. Deleting the LICENSE file is also a major red flag. Please limit the PR to only the feature you're trying to implement!

> Not familiar with golang, I got the official webdav lib and modified some private methods to public, in order to return a virtual dir of the scopes when requesting the "/" url.
> In addition, serveral src files were renamed to avoid the duplicate and some config options I thought useless were canceled.

If you need a primer on Go, go through the Go tour: https://tour.golang.org/welcome/1.

**Comment by Travalone** [comment]
> > > This does more than apply multi scopes for each user. Was this a mistake?
> > 
> > 
> > Not clear what u mean. I just adjusted the config options according to my personal habit, imitating FileZilla.
> > My main purpose is the multi scopes for each user, and I used the Prefix to implement it.
> 
> Click on the `Files changed` tab and see all your changes there. You've deleted many necessary files and code, renamed/removed the proper module path from being `github.com/hacdias/webdav/v3`, added your IDE's files, and much more. Deleting the LICENSE file is also a major red flag. Please limit the PR to only the feature you're trying to implement!
> 
> > Not familiar with golang, I got the official webdav lib and modified some private methods to public, in order to return a virtual dir of the scopes when requesting the "/" url.
> > In addition, serveral src files were renamed to avoid the duplicate and some config options I thought useless were canceled.
> 
> If you need a primer on Go, go through the Go tour: https://tour.golang.org/welcome/1.

Yeah that's a mistake when some changes were once lost. Sorry for that, and I would fix it.

**Pull request closed without merging**
